# Generated by Django 2.1.4 on 2019-01-04 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_aws', models.CharField(max_length=200)),
                ('program_aws', models.CharField(max_length=200)),
                ('loan_amt_aws', models.CharField(max_length=200)),
                ('reserve_aws', models.CharField(max_length=200)),
                ('fico_aws', models.CharField(max_length=200)),
                ('doc_aws', models.CharField(max_length=200)),
                ('purch_rt_aws', models.CharField(max_length=200)),
                ('cash_out_aws', models.CharField(max_length=200)),
                ('dti_aws', models.CharField(max_length=200)),
                ('ltv_aws', models.CharField(max_length=200)),
                ('second_home_aws', models.CharField(max_length=200)),
                ('prop_type_aws', models.CharField(max_length=200)),
                ('io_aws', models.CharField(max_length=200)),
                ('amort_aws', models.CharField(max_length=200)),
                ('final_matur_aws', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_text', models.CharField(max_length=200)),
                ('program_text', models.CharField(max_length=200)),
                ('loan_amt_text', models.CharField(max_length=200)),
                ('reserve_text', models.CharField(max_length=200)),
                ('fico_text', models.CharField(max_length=200)),
                ('doc_text', models.CharField(max_length=200)),
                ('purch_rt_text', models.CharField(max_length=200)),
                ('cash_out_text', models.CharField(max_length=200)),
                ('dti_text', models.CharField(max_length=200)),
                ('ltv_text', models.CharField(max_length=200)),
                ('second_home_text', models.CharField(max_length=200)),
                ('prop_type_text', models.CharField(max_length=200)),
                ('io_text', models.CharField(max_length=200)),
                ('amort_text', models.CharField(max_length=200)),
                ('final_matur_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realapp.QuestionReal'),
        ),
    ]
